### PR TITLE
Upgrade to fs2 0.10-RC2

### PR DESCRIPTION
**Pull request by SystemFw**
This PR upgrades fs2-reactive-streams to fs2 0.10-RC2.
As part of it, it also reimplements `StreamSubscription`, which was using `unconsAsync` that we've now removed

### CODE REVIEW

**Review by aeons — APPROVED** [review]
:+1:

**Comment by zainab-ali** [comment]
Awesome!  Thanks for all the hard work! 👍

**Comment by zainab-ali** [comment]
@SystemFw apologies for not asking earlier, are you happy being listed as a contributor?

**Comment by SystemFw** [comment]
Sure :)

**Pull request merged**
