### PR TITLE
Update to fs2-0.10.0 and cats-effect

### PR DESCRIPTION
**Pull request by aeons**
I updated the fs2 dependency to 0.10.0-M1 and updated the implementation to use the `cats-effect` typeclasses and the new async utility functions in `fs2.async`.

This is not something to merge now, but I needed this for something else, so I thought I might as well push it here.

(and great talk saturday at Typelevel Summit, btw :) )

### CODE REVIEW

**Comment by zainab-ali** [comment]
Thanks @aeons ! This will save me a lot of work.

**Comment by aeons** [comment]
`fs2-0.10.0-M2` came with a bunch of API changes. I've tried to translate the existing code directly, and all tests pass.

**Comment by zainab-ali** [comment]
Thanks!  I was planning on releasing for 0.10.0, but would be happy to release for the milestone if required.  Do you need a release for M2?

**Comment by aeons** [comment]
I think a release would be nice. AFAIK M2 has the API that will be in the final version.

**Comment by aeons** [comment]
@zainab-ali would you create a release for `fs2-0.10.0-M2`?

**Comment by zainab-ali** [comment]
Sorry for the delay! I've now released 0.2.0 which is dependent on 0.10.0-M2

**Comment by aeons** [comment]
Thanks!

**Pull request merged**
